### ISSUE TITLE
How to add additional games to the `cloudretro` demo?

### ISSUE THREAD

**Issue by calexandre** [l7mp/stunner#26]
I would like to test additional games on the `cloudretro` demo... more importantly, I would like to test two player games for a personal project.

I already tried to add more `nes` roms to the image, but the `cloudretro` demo only loads with the Super Mario Bros game.

@bbalint105 could you shed some light on how can we add additional roms to the base image? 

Thank you!

**Comment by bbalint105** [comment]
Hello again,

And of course, it is indeed possible!

If you check (this) repo out, I've used this with minor edits compared to the original project.
Mainly because our demo focuses on using and introducing stunner, and it doesnt include a shared storage or file servers setup like NFS.
Thus, the games get compiled into the image.

They take place in the assets/games folder, if you clone the mentioned repo and add some games to it, you can build the same image the demo uses, but of course, with your games.

If you run into unexpected issues, I will try my best to help, although for some days, I am a bit limited by hardware and time.

**Comment by nmate** [comment]
Hi @calexandre,
If you would feel like to have a discussion about specific use-cases for STUNner, just let us know via info-at-l7mp.io! We are interested in the set of possible use-cases and the current limitations.

**Comment by calexandre** [comment]
Thank you!
Will sure do..
Currently we are using STUNner to test our 5G Edge sites for mobile computing purposes, which includes radio communications (using 5G technology).

**Comment by rg0now** [comment]
Dear @calexandre, I'm closing this issue in the hope that we have covered the problem. Feel free to reopen!
