### ISSUE TITLE
[Inquiry] general progress and roadmap of this project

### ISSUE THREAD

**Issue by imcom** [l7mp/stunner#8]
Hi l7mp team!

Great work as it seems to be, we are interested in this project which makes webrtc+k8s plausible.

Just wondering what's the current status in terms of the _Milestones_ for this project? Is there any timeline/roadmap we can follow?

Currently we run a hybrid topology for our media streaming, we host `coturn` servers in a public cloud and this `coturn` cluster colocates with a bunch of media servers (along with application servers) all hosted in k8s. Feature-wise it is just fine but it surely lacks of scalability and visibility

**Comment by rg0now** [comment]
Hi, thanks for the inquiry. 

The milestones are not, well, set in stone: we're constantly changing the roadmap as we experiment with STUNner and see the missing features. Currently the major painpoint is the Kubernetes operator to wrap the low-level STUNner configs in high-level Kubernetes-like YAMLs/CRDs. After we have that in place (1-2 releases from now) we will look into scalabilty and observability a bit more. Note that scaling up STUNner and the media servers behind it is already super-simple, but scaling down may remove active sessions so that's not optimal. We have a couple of ideas on how to handle that, we expect a working PoC in 1-2 months.  Best would be to check back then, but feel free to join the Discord, most discussions and planning happens there.

**Comment by imcom** [comment]
Hi @rg0now, your kind answer is such a great reading, really appreciated! Things got busy lately so could read it through earlier. Without eBPF tuning, a single pod should still be able to handle around ~500Kpps I assume? Probably STUNner can also take advantage of the `Cilium` network in k8s directly?

**Comment by rg0now** [comment]
Last time we checked we got >1.2 mpps packet rates with a fairly naive UDP proxy attached to the eBPF/tc hook, and around 1.7 mpps with eBPF/XDP. We hope to get similar numbers with the STUNner accelerator too, but note that handling the specifics of the TURN wire protocol in eBPF will not be trivial and it may have its performance penalty. I guess at these speeds it will be the Kubernetes CNI or the cloud infra that become a bottleneck, and not STUNner. But it's quite fast already: you can easily get 1--2 kpps without any acceleration, with vanilla STUNner. We hope to release some benchmark results soon! 

As per Cilium: as much as we are massive fans of Cilium, unfortunately we cannot use it right away: the Cilium data-plane does not know how to handle the STUN/TURN protocol formats. But we at least hope to avoid any interference with it, which will be a challenge in itself given how Cilium uses the same eBPF kernel hooks we also intend to use. We'll see!

**Comment by rg0now** [comment]
> 1-2 kpps for one RTP stream right?

It's actually multiple iperf UDP streams encapsulated in separate TURN streams; details will follow soon.

I close this PR now, but feel free to reopen anytime.
